# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ""
logo: "/assets/images/logoMarcelo.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Artículos acerca de Redes Informáticas y Ciberseguridad
twitter_username: username
github_username: username
minimal_mistakes_skin: haxor
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/ # Para que aparezca Home/Posts
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marcelo Tiburcio"
  avatar : "/assets/images/fotoPerfil.png"
  bio    : "Ingeniería Electrónica<br>Universidad Nacional de Ingeniería (UNI)<br>- Redes Informáticas (CCNA)<br>- Practical Ethical Hacking<br>- Pentesting<br>- Capture the Flag (CTFs)<br>- Active Directory<br>- Escalada de privilegios en Windows y Linux<br>- Bash, Python, Java"
  location: "Lima, Perú"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url : "mailto:marcelo032803@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url : "https://www.linkedin.com/in/mtiburcio/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    # - label: "Email"
    #   icon: "fas fa-fw fa-envelope"
    #   url : "mailto:marcelo032803@gmail.com"
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin"
    #   url : "https://www.linkedin.com/in/mtiburcio/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: false
      show_date: true
      toc: true
      toc_label: "Índice"
      toc_icon: "file-alt"
      toc_sticky: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

enable_copy_code_button: true   # Botón de copia de bloque de código

# Búsqueda en el sitio
lunr:
  search_within_pages: true

# Anula configuración de lunr que busca las primeras 50 palabras
search_full_content: true

#Activar migas de pan
breadcrumbs: true  # disabled by default
